// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlr2QfqPYkSV-HyNDlexxMJKQqagNFU7A',
    appId: '1:1043468791813:web:509df7120775557919ac6c',
    messagingSenderId: '1043468791813',
    projectId: 'doctorapp-ac85b',
    authDomain: 'doctorapp-ac85b.firebaseapp.com',
    storageBucket: 'doctorapp-ac85b.firebasestorage.app',
    measurementId: 'G-H86RS1KMR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO10-XrJt3aA3Jyv8CmQ3f-WMbl4ODbus',
    appId: '1:1043468791813:android:74f51e9e81ee0d7c19ac6c',
    messagingSenderId: '1043468791813',
    projectId: 'doctorapp-ac85b',
    storageBucket: 'doctorapp-ac85b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUmVd0K-euVEjTzFtnG-qMHxqh9wgl1aE',
    appId: '1:1043468791813:ios:6460d2425c129d3219ac6c',
    messagingSenderId: '1043468791813',
    projectId: 'doctorapp-ac85b',
    storageBucket: 'doctorapp-ac85b.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUmVd0K-euVEjTzFtnG-qMHxqh9wgl1aE',
    appId: '1:1043468791813:ios:6460d2425c129d3219ac6c',
    messagingSenderId: '1043468791813',
    projectId: 'doctorapp-ac85b',
    storageBucket: 'doctorapp-ac85b.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlr2QfqPYkSV-HyNDlexxMJKQqagNFU7A',
    appId: '1:1043468791813:web:8f9b9272d69c8a4319ac6c',
    messagingSenderId: '1043468791813',
    projectId: 'doctorapp-ac85b',
    authDomain: 'doctorapp-ac85b.firebaseapp.com',
    storageBucket: 'doctorapp-ac85b.firebasestorage.app',
    measurementId: 'G-05ZFKC9ZXC',
  );

}